### ISSUE TITLE
X button on task card does not delete card

### ISSUE THREAD

**Issue by aweissman11** [dreardon1021/CheckYourselfFinal1#13]
Expected behavior: clicking on the X button on the cards should delete the card from the list.

Current behavior: clicking on the X button does not do anything

**Comment by dreardon1021** [comment]
I agree with you here on functionality and whats expected. However the rubric wanted what is below. I would make changes in the future for how you and I expect it to work

Deleting an Existing ToDo Card
After creating a todo card, the user should be able to remove it once they have completed their checklist.

Each todo card on the todo list should have a button to remove it from both the data model and the DOM.
The “Delete” button should only be enabled if all of the tasks on the checklist have been checked off.
Upon clicking the “Delete” button, the appropriate todo list should be removed from the DOM.
The update of the data model should happen in the deleteFromStorage method that is defined in the ToDoList class.
How the DOM gets updated using JavaScript should happen in the main.js file
